##Course Project 
## Loading the libraries needed for the project

library(caret)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(rattle)
library(randomForest)
## Downloading the file
fileURL <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
download.file(fileURL,destfile="./training_data.csv",method="curl")
# reading the training file to R
training <- read.csv("./training_data.csv",header=T)

# reading the test data into R
fileURL <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
download.file(fileURL,destfile="./test_data.csv",method="curl")
testing <- read.csv("./test_data.csv",header=T)

## No of rows and columns in training
dim(training)

## removing cols that have NA from training
new_data <- training[ , ! apply( training , 2 , function(x) any(is.na(x)) ) ]

## removing the timestamp columns and sequence data from new data set
new_data<-new_data[,-c(1:7)]



## Checking for near zero variables

nsv <- nearZeroVar(new_data, saveMetrics=FALSE)
nsv
## using only columns that do not have nsv
new_data <- new_data[,-(nsv)]
dim(new_data)


## Reproduceability 
set.seed(100)
## Dividing the data into training and test
inTrain <- createDataPartition(new_data$classe,p=0.7,list=F)
train_set <- new_data[inTrain,]
test_set <- new_data[-inTrain,]

## Ensuring the testing data set provided also has the same no of columns as the training set
## removing the classe column
testing <- testing[new_data[,-53]]

##Model Building : Using "rpart" - decision tree algorithm
modFit<-train(classe~.,method = "rpart",data=train_set)
fancyRpartPlot(modFit$finalModel)

## Predicting...
pred_rpart<-predict(modFit,test_set)

## Confusion Matrix to test and report the results
results<-confusionMatrix(pred_rpart,test_set$classe)
print(results)

### As accuracy is very low with rpart, lets try building with randomForest
## Model Building using Random forest algorithm
model_rf <- randomForest(classe~.,data=train_set)
##Predictions:
pred_rf <-predict(model_rf,test_set)
## ConfusionMatrix to publish results
results_rf<-confusionMatrix(pred_rf,test_set$classe)
print(results_rf)

##Accuracy is 99.58% with Random Forest. We will use this model to predict against the test
## set of 20 observations provided.

predictTest <- predict(model_rf,testing)
## print the results of prediction
print(predictTest)


